"""The 28 Stage-1 logical roles. 7 are true LLM agents; 21 are deterministic services."""

AGENT_ROLES = [
    # --- LLM agents ---
    {"key": "intent_classifier", "name": "Intent Classifier", "kind": "llm", "group": "Intelligence",
     "description": "Classifies GSC queries into transactional/commercial/informational/navigational with confidence.",
     "model_tier": "cheap"},
    {"key": "cannibalization_judge", "name": "Cannibalization Judge", "kind": "llm", "group": "Intelligence",
     "description": "Adjudicates ambiguous query x URL conflicts the deterministic rules could not resolve.",
     "model_tier": "cheap"},
    {"key": "competitor_delta_explainer", "name": "Competitor Delta Explainer", "kind": "llm", "group": "Competitors",
     "description": "Explains why a competitor URL outranks ours for a given query and market.", "model_tier": "reasoning"},
    {"key": "content_outline_agent", "name": "Content Outline / Draft Agent", "kind": "llm", "group": "Content",
     "description": "Produces evidence-backed outlines and drafts. Stage 1: stored, previewed, never published.",
     "model_tier": "reasoning"},
    {"key": "outreach_draft_agent", "name": "Outreach Draft Agent", "kind": "llm", "group": "Content",
     "description": "Drafts link outreach. Stage 1: auto-send is DENY at the policy layer.", "model_tier": "reasoning"},
    {"key": "learning_summarizer", "name": "Learning Summarizer", "kind": "llm", "group": "Memory",
     "description": "Converts outcomes into memory records with evidence, confidence and sample size.",
     "model_tier": "cheap"},
    {"key": "orchestrator", "name": "Orchestrator (Planner)", "kind": "llm", "group": "Control",
     "description": "Plans nightly pipeline order and budget allocation. Planner only, never an executor.",
     "model_tier": "reasoning"},
    # --- Deterministic services ---
    {"key": "shopify_sync", "name": "Shopify Sync Service", "kind": "service", "group": "Ingest",
     "description": "Cursor-paginated full pull, webhooks, nightly reconciliation. Read-only scopes."},
    {"key": "gsc_ingest", "name": "GSC Ingest Service", "kind": "service", "group": "Ingest",
     "description": "BigQuery bulk export primary; Search Analytics API for bootstrap + backfill."},
    {"key": "crawler", "name": "Technical Crawler", "kind": "service", "group": "Technical",
     "description": "Queue-driven incremental crawl with per-host politeness. No fixed URL cap."},
    {"key": "tiering", "name": "Tiering Service", "kind": "service", "group": "Intelligence",
     "description": "Recomputes dynamic A/B/C/D tiers nightly from percentile rank of opportunity score."},
    {"key": "opportunity_scoring", "name": "Opportunity Scoring Engine", "kind": "service", "group": "Intelligence",
     "description": "0-100 score from demand, position gap, CTR gap, intent value and technical health."},
    {"key": "rank_tracker", "name": "Rank Tracker", "kind": "service", "group": "Competitors",
     "description": "Tracks position history per query x market x device."},
    {"key": "serp_snapshotter", "name": "SERP Snapshotter", "kind": "service", "group": "Competitors",
     "description": "Budget-gated SERP capture for Tier A and high-opportunity entities only."},
    {"key": "indexation_rules", "name": "Indexation Rules Engine", "kind": "service", "group": "Technical",
     "description": "Evaluates robots, meta robots, canonicals and status codes for indexability."},
    {"key": "schema_validator", "name": "Schema Validator", "kind": "service", "group": "Technical",
     "description": "Validates Product/Offer/BreadcrumbList/FAQ structured data."},
    {"key": "cwv_monitor", "name": "Core Web Vitals Monitor", "kind": "service", "group": "Technical",
     "description": "PageSpeed Insights sampling, budget-gated, per template."},
    {"key": "internal_link_graph", "name": "Internal Link Graph", "kind": "service", "group": "Technical",
     "description": "Builds the link graph, finds orphans and link-equity bottlenecks."},
    {"key": "backlink_diff", "name": "Backlink Diff Service", "kind": "service", "group": "Competitors",
     "description": "Diffs referring domains over time. Discovery only in Stage 1."},
    {"key": "keyword_clusterer", "name": "Keyword Clusterer", "kind": "service", "group": "Intelligence",
     "description": "Clusters the keyword universe by SERP overlap and intent."},
    {"key": "experiment_runner", "name": "Experiment Runner", "kind": "service", "group": "Experiments",
     "description": "Stage 1: schema only. No execution."},
    {"key": "anomaly_detector", "name": "Anomaly Detector", "kind": "service", "group": "Intelligence",
     "description": "Flags statistically significant drops in clicks, impressions or position."},
    {"key": "qa_validator", "name": "QA Validator", "kind": "service", "group": "Control",
     "description": "Validates every pipeline output before it reaches the dashboard."},
    {"key": "cost_ledger", "name": "Cost Ledger", "kind": "service", "group": "Control",
     "description": "Intercepts every paid call. Per-provider caps plus a global monthly ceiling."},
    {"key": "notification_engine", "name": "Notification Engine", "kind": "service", "group": "Control",
     "description": "In-app alerts at 50/75/90/100% budget and on critical technical regressions."},
    {"key": "policy_engine", "name": "Safety Policy Engine", "kind": "service", "group": "Control",
     "description": "GREEN/YELLOW/RED action classes. All Shopify writes compile to DENY in Stage 1."},
    {"key": "memory_store", "name": "Memory Store", "kind": "service", "group": "Memory",
     "description": "Persists business, SEO-knowledge, failure and decision records with recheck dates."},
    {"key": "audit_log", "name": "Audit Log", "kind": "service", "group": "Control",
     "description": "Append-only, hash-chained per UTC day. Every action and API call."},
]

ROLE_BY_KEY = {r["key"]: r for r in AGENT_ROLES}
